# Generated by Django 4.2.9 on 2024-01-20 13:15

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=places.models.user_directory_path, verbose_name='Файл'),
        ),
    ]
