# Generated by Django 3.2.12 on 2022-03-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
